#!/bin/bash
# This is sourced. Fake bang-path to help editors and linters
# shellcheck disable=SC2034  # don't warn about unused variables

# Patterns to exclude from linting, anything starting with this will be excluded
excluded_prefixes+=(
)

# Exclude specific files by specifying their entire filename as listed by 'olint'.
excludes+=(
)
